@startuml

|管理员|
start
:登录;
if (登录成功?) then (是)
  :显示管理菜单;
  :选择功能;
  if (添加图书?) then (是)
    :输入图书信息;
    :添加图书;
    :显示添加成功提示;
  else if (编辑图书?) then (是)
    :选择要编辑的图书;
    :修改图书信息;
    :保存修改;
    :显示修改成功提示;
  else if (删除图书?) then (是)
    :选择要删除的图书;
    if (图书未被借出?) then (是)
      :确认删除;
      :删除图书;
      :显示删除成功提示;
    else (否)
      :显示删除失败提示;
    endif
  else if (查看图书库存?) then (是)
    :显示图书库存信息;
  else if (更新图书库存?) then (是)
    :选择要更新库存的图书;
    :输入更新数量;
    :更新图书库存;
    :显示更新成功提示;
  else if (此图书未被借出?) then (是)
    :选择要查看的图书;
    :显示图书信息和借阅记录;
  endif
else (否)
  :显示登录失败提示;
endif
:退出登录;
stop

@enduml


@startuml

|用户|
start
:登录;
:搜索图书;
if (搜索结果为空?) then (是)
  :显示无结果提示;
else (否)
  :显示搜索结果;
endif
:选择图书;
:查看图书详情;
if (已借阅该书?) then (是)
  :显示借阅信息;
else (否)
  if (已登录?) then (是)
    :显示借阅按钮;
  else (否)
    :显示登录提示;
  endif
endif
:借阅图书;
if (借阅成功?) then (是)
  :显示借阅成功提示;
else (否)
  :显示借阅失败提示;
endif
:返回首页;
:退出登录;
stop


@enduml



@startuml

|用户|
start
:登录;
:搜索图书;
if (搜索结果为空?) then (是)
  :显示无结果提示;
else (否)
  :显示搜索结果;
endif
:选择图书;
:查看图书详情;
if (已借阅该书?) then (是)
  :显示借阅信息;
else (否)
  if (已登录?) then (是)
    :显示借阅按钮;
  else (否)
    :显示登录提示;
  endif
endif
:借阅图书;
if (借阅成功?) then (是)
  :显示借阅成功提示;
else (否)
  :显示借阅失败提示;
endif
:返回首页;
|管理员|
:登录;
if (登录成功?) then (是)
  :显示管理菜单;
  :选择功能;
  if (添加图书?) then (是)
    :输入图书信息;
    :添加图书;
    :显示添加成功提示;
  else if (编辑图书?) then (是)
    :选择要编辑的图书;
    :修改图书信息;
    :保存修改;
    :显示修改成功提示;
  else if (删除图书?) then (是)
    :选择要删除的图书;
    if (图书未被借出?) then (是)
      :确认删除;
      :删除图书;
      :显示删除成功提示;
    else (否)
      :显示删除失败提示;
    endif
  else if (查看图书库存?) then (是)
    :显示图书库存信息;
  else if (更新图书库存?) then (是)
    :选择要更新库存的图书;
    :输入更新数量;
    :更新图书库存;
    :显示更新成功提示;
  else if (此图书未被借出?) then (是)
    :选择要查看的图书;
    :显示图书信息和借阅记录;
  endif
else (否)
  :显示登录失败提示;
endif

|用户|
:退出登录;
stop

@enduml