# Generated by Django 2.2.28 on 2022-04-26 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('aid', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('aimg', models.CharField(blank=True, max_length=500, null=True)),
                ('aname', models.CharField(blank=True, max_length=32, null=True)),
                ('adesc', models.CharField(blank=True, max_length=2000, null=True)),
            ],
            options={
                'db_table': 'author',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('bid', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('bstar', models.CharField(blank=True, max_length=20, null=True)),
                ('bimg', models.CharField(blank=True, max_length=100, null=True)),
                ('bname', models.CharField(blank=True, max_length=20, null=True)),
                ('bpublisher', models.CharField(blank=True, max_length=20, null=True)),
                ('btime', models.CharField(blank=True, max_length=20, null=True)),
                ('bprice', models.CharField(blank=True, max_length=20, null=True)),
                ('bdesc', models.CharField(blank=True, max_length=2000, null=True)),
                ('bnum', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'db_table': 'book',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('cid', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('cstar', models.CharField(blank=True, max_length=20, null=True)),
                ('cdesc', models.CharField(blank=True, max_length=1000, null=True)),
            ],
            options={
                'db_table': 'comment',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Sort',
            fields=[
                ('sid', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('sname', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'db_table': 'sort',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('uid', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('uemail', models.CharField(blank=True, max_length=20, null=True)),
                ('usex', models.CharField(blank=True, max_length=20, null=True)),
                ('uname', models.CharField(blank=True, max_length=20, null=True)),
                ('upsw', models.CharField(blank=True, max_length=100, null=True)),
                ('uphone', models.CharField(blank=True, max_length=20, null=True)),
                ('uadmin', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'user',
                'managed': False,
            },
        ),
    ]
