# Generated by Django 2.2.28 on 2022-04-27 07:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('cid', models.AutoField(primary_key=True, serialize=False)),
                ('pnum', models.IntegerField()),
                ('sumprice', models.CharField(max_length=64)),
                ('time', models.DateField(auto_now_add=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='book_cat', to='index.Book')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_cat', to='index.User')),
            ],
        ),
        migrations.CreateModel(
            name='PayCart',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carttopay', to='index.Cart')),
            ],
        ),
        migrations.CreateModel(
            name='myorder',
            fields=[
                ('order_id', models.AutoField(primary_key=True, serialize=False)),
                ('ordernum', models.CharField(max_length=32)),
                ('allprice', models.FloatField()),
                ('allpnum', models.IntegerField()),
                ('address', models.CharField(max_length=255)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='book_order', to='index.Book')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_order', to='index.User')),
            ],
        ),
    ]
